name: comunicacion1_0
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.3
  intl: ^0.20.2
  permission_handler: ^11.4.0
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
